# Generated by Django 4.1.13 on 2024-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.FloatField(max_length=30)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
