# Generated by Django 5.1 on 2024-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessManager',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('qualification_id', models.IntegerField()),
                ('designation_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_fitness manager',
                'managed': False,
            },
        ),
    ]
