# Generated by Django 4.2.15 on 2024-11-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_clientfm_clientfm2_designations_eatinghabit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientfm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientfm2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='designations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eatinghabit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eatinghabit2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fitnessmanager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmskills',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fooddatabase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentalfitness',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qualifications',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
    ]
