# Generated by Django 4.2.15 on 2024-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_fitnessmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_designations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=50)),
                ('certification', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_qualifications',
                'managed': False,
            },
        ),
    ]
