# Generated by Django 4.2.15 on 2024-08-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_designations_qualifications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fitnessmanager',
            table='tbl_fitness_manager',
        ),
    ]
