# Generated by Django 4.2.15 on 2025-01-06 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_client_options_alter_clientfm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientfm',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientfm2',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='designations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eatinghabit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eatinghabit2',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fitnessmanager',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fmskills',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fooddatabase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mentalfitness',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qualifications',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='App.product')),
            ],
        ),
    ]
