# Generated by Django 4.2.15 on 2024-09-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_fitnessmanager_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('service_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_plans',
                'managed': False,
            },
        ),
    ]
