# Generated by Django 4.2.15 on 2024-09-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_fooddatabase_delete_nutrition_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_no', models.IntegerField()),
                ('service_type', models.CharField(max_length=100)),
                ('workout_id', models.IntegerField()),
                ('nutrition_id', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('body_part', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('workout_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_workouts',
                'managed': False,
            },
        ),
    ]
