# Generated by Django 4.2.15 on 2024-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_service_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDatabase',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('food_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_food_database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('nutrition_id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrition_no', models.IntegerField(unique=True)),
                ('food_id', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tbl_nutritions',
                'managed': False,
            },
        ),
    ]
