# Generated by Django 4.2.15 on 2024-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_fooddatabase_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('fm_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=50)),
                ('fm_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_client_fm',
                'managed': False,
            },
        ),
    ]
