# Generated by Django 4.2.15 on 2024-10-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_clientfm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFM2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('fm_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=50)),
                ('fm_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_clientfm2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EatingHabit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habit', models.CharField(max_length=50)),
                ('food_item', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_food_habits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message_text', models.CharField(max_length=1000)),
                ('message_reply', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tbl_messages',
                'managed': False,
            },
        ),
    ]
