# Generated by Django 4.2.15 on 2024-10-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_clientfm2_eatinghabit_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingHabit2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('fm_id', models.IntegerField()),
                ('habit_no', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_eating_habit',
                'managed': False,
            },
        ),
    ]
