# Generated by Django 4.2.15 on 2024-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_eatinghabit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('star_rating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_feedback',
                'managed': False,
            },
        ),
    ]
