# Generated by Django 4.2.15 on 2024-10-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_mentalfitness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('starting_value', models.IntegerField()),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_goal',
                'managed': False,
            },
        ),
    ]
