# Generated by Django 4.2.15 on 2024-10-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('starting_bmi', models.FloatField()),
                ('target_bmi', models.FloatField()),
                ('current_bmi', models.FloatField()),
                ('current_bmi_date', models.DateField()),
            ],
            options={
                'db_table': 'tbl_progress',
                'managed': False,
            },
        ),
    ]
