# Generated by Django 4.2.15 on 2024-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fm_id', models.IntegerField()),
                ('gym_pic', models.FileField(blank=True, null=True, upload_to='gym_pic/')),
                ('skills', models.CharField(max_length=500)),
                ('achievements', models.CharField(max_length=500)),
                ('achievement_proof', models.FileField(blank=True, null=True, upload_to='achievement_proof/')),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_fm_skills',
                'managed': False,
            },
        ),
    ]
